# Generated by Django 5.0.6 on 2024-06-21 15:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioUser',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(default='Desconhecido', max_length=300)),
                ('pais', models.CharField(default='Desconhecido', max_length=300)),
                ('cor', models.CharField(default='Desconhecido', max_length=200)),
                ('nicho', models.CharField(default='Desconhecido', max_length=200)),
                ('link_store', models.URLField(default='Desconhecido')),
                ('url_loja', models.URLField(default='Desconhecido')),
                ('plan', models.BooleanField(default=False)),
                ('token_senha', models.CharField(default='Desconhecido', max_length=200)),
                ('chave_de_api', models.CharField(default='Desconhecido', max_length=200)),
                ('chave_secreta', models.CharField(default='Desconhecido', max_length=200)),
                ('produt', models.BooleanField(default=False)),
                ('banners', models.BooleanField(default=False)),
                ('telefone', models.CharField(default='Desconhecido', max_length=300)),
                ('email_suporte', models.EmailField(default='Desconhecido', max_length=254)),
                ('empresa', models.CharField(default='Desconhecido', max_length=300)),
                ('business_hours', models.CharField(default='Desconhecido', max_length=300)),
                ('lojaproduzida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
